export enum IconType {
  ARROW_LEFT = 'arrow-left',
  ARROW_RIGHT = 'arrow-right',
  ROTATE_CW = 'rotate-cw',
  ROTATE_CCW = 'rotate-ccw',
  BACK = 'back',
  CLOSE = 'close',
  HOME = 'home',
  HONBA = 'honba',
  INFO = 'info',
  LINK = 'link',
  LOG = 'log',
  LOSE = 'lose',
  NEXT = 'next',
  PLUS = 'plus',
  QR = 'qr',
  REFRESH = 'refresh',
  REPEAT = 'repeat',
  RIICHI_BIG = 'riichi-big',
  RIICHI_SMALL = 'riichi-small',
  SAVE = 'save',
  SETTINGS = 'settings',
  SHUFFLE = 'shuffle',
  WIN = 'win',
}
