/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

export interface Achievements {
  /**
   * achievements precalculated data
   */
  data: string;
  event_id: number;
  id: number;
  last_update: string | null;
}

export interface Event {
  __deprecated_is_textlog: string | null;
  allow_player_append: number;
  allow_view_other_tables: number;
  auto_seating: number;
  description: string;
  end_time: string | null;
  finished: number;
  /**
   * for timer, duration in seconds
   */
  game_duration: number | null;
  games_status: string | null;
  hide_achievements: number;
  hide_results: number;
  id: number;
  is_listed: number;
  is_online: number;
  is_prescripted: number;
  is_team: number;
  /**
   * for timer, unix datetime of last started timer
   */
  last_timer: number | null;
  /**
   * tenhou lobby id for online events
   */
  lobby_id: number | null;
  min_games_count: number;
  next_game_start_time: number;
  platform_id: number | null;
  /**
   * timer red zone amount in seconds, or null to disable red zone
   */
  red_zone: number | null;
  /**
   * table rules, either in JSON or as a predefined ID
   */
  ruleset: string | null;
  ruleset_changes: string;
  ruleset_config: string;
  series_length: number;
  sort_by_games: number;
  start_time: string | null;
  /**
   * host of statistics frontend
   */
  stat_host: string;
  sync_end: number;
  sync_start: number;
  time_to_start: number;
  timezone: string;
  title: string;
  use_penalty: number;
  use_timer: number;
}

export interface EventPrescript {
  event_id: number;
  id: number;
  next_game: number;
  /**
   * predefined event seating script
   */
  script: string;
}

export interface EventRegisteredPlayers {
  event_id: number;
  id: number;
  ignore_seating: number;
  local_id: number | null;
  player_id: number;
  replacement_id: number | null;
  team_name: string | null;
}

export interface GamePlatforms {
  id: number;
  platform_id: number;
  platform_name: string;
}

export interface JobsQueue {
  created_at: string;
  id: number;
  job_arguments: string;
  job_name: string;
}

export interface Penalty {
  amount: number;
  assigned_by: number;
  cancelled: number;
  cancelled_reason: string | null;
  created_at: string;
  event_id: number;
  id: number;
  player_id: number;
  reason: string;
  session_id: number | null;
}

export interface PlayerHistory {
  avg_place: number;
  chips: number | null;
  event_id: number;
  games_played: number;
  id: number;
  player_id: number;
  rating: number;
  session_id: number;
}

export interface PlayerStats {
  /**
   * stats precalculated data
   */
  data: string;
  event_id: number;
  id: number;
  last_update: string | null;
  player_id: number;
}

export interface Round {
  /**
   * dora count
   */
  dora: number | null;
  end_date: string | null;
  event_id: number;
  fu: number | null;
  han: number | null;
  id: number;
  kandora: number | null;
  kanuradora: number | null;
  /**
   * session intermediate results before this round was registered
   */
  last_session_state: string | null;
  /**
   * not null only on ron or chombo
   */
  loser_id: number | null;
  /**
   * double or triple ron flag to properly display results of round
   */
  multi_ron: number | null;
  nagashi: string | null;
  /**
   * boolean, was winner's hand opened or not
   */
  open_hand: number | null;
  /**
   * ron, tsumo, draw, abortive draw or chombo
   */
  outcome: string;
  pao_player_id: number | null;
  /**
   * comma-separated list of user ids who called riichi
   */
  riichi: string | null;
  /**
   * 1-4 means east1-4, 5-8 means south1-4, etc
   */
  round: number;
  session_id: number;
  /**
   * comma-separated list of tempai user ids
   */
  tempai: string | null;
  uradora: number | null;
  /**
   * not null only on ron or tsumo
   */
  winner_id: number | null;
  /**
   * comma-separated yaku id list
   */
  yaku: string | null;
}

export interface Session {
  end_date: string | null;
  event_id: number;
  extra_time: number;
  id: number;
  /**
   * json-encoded results for in-progress sessions
   */
  intermediate_results: string | null;
  okr_ignore: number;
  /**
   * original tenhou game link, for access to replay
   */
  orig_link: string | null;
  /**
   * tenhou game hash, for deduplication
   */
  replay_hash: string | null;
  /**
   * hash to find this game from client mobile app
   */
  representational_hash: string | null;
  start_date: string | null;
  /**
   * planned / inprogress / prefinished / finished
   */
  status: string | null;
  /**
   * table number in tournament
   */
  table_index: number | null;
}

export interface SessionPlayer {
  id: number;
  order: number;
  player_id: number;
  session_id: number;
}

export interface SessionResults {
  chips: number | null;
  event_id: number;
  id: number;
  place: number;
  player_id: number;
  /**
   * resulting score after uma/oka and starting points subtraction
   */
  rating_delta: number;
  /**
   * how many points player has at the end, before any uma/oka calc
   */
  score: number;
  session_id: number;
}

export interface Yaku {
  id: number;
  name: string;
}

export interface DB {
  achievements: Achievements;
  event: Event;
  event_prescript: EventPrescript;
  event_registered_players: EventRegisteredPlayers;
  game_platforms: GamePlatforms;
  jobs_queue: JobsQueue;
  penalty: Penalty;
  player_history: PlayerHistory;
  player_stats: PlayerStats;
  round: Round;
  session: Session;
  session_player: SessionPlayer;
  session_results: SessionResults;
  yaku: Yaku;
}
