# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

notifications:
  slack: furiten:6fzHMN5l1JM8rgfv5PXg4dmU

services:
  - mysql
  - postgresql

install: make deps

# list any PHP version you want to test against
php:
  # using major version aliases

  # aliased to a recent 5.5.x version
  - 5.5
  # aliased to a recent 5.6.x version
  - 5.6
  # aliased to a recent 7.x version
  - 7.0

before_script:
  - phpenv config-add tests/php-disable-http-raw.ini
  - mysql -e 'create database api_test;'
  - psql -c 'create database api_test;' -U postgres
  - mkdir -p tests/data && echo '' > tests/data/db.sqlite
  - echo 'Current working directory:' `pwd`

script:
- bin/phinx migrate -e testing # this will test sqlite
- bin/phinx migrate -e travis_mysql
- bin/phinx migrate -e travis_pgsql
- ls -la tests/data
- make check_ci
