[supervisord]
user             = root
nodaemon         = true
logfile          = /dev/stderr
logfile_maxbytes = 0
loglevel         = debug

[inet_http_server]
port=127.0.0.1:9001

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://127.0.0.1:9001

[program:rsyslog]
command         = rsyslogd -n
autostart       = true
autorestart     = true
startsecs       = 2
stopwaitsecs    = 2
stdout_logfile  = /dev/stdout
stderr_logfile  = /dev/stderr
stdout_logfile_maxbytes = 0
stderr_logfile_maxbytes = 0

[program:nginx]
command         = nginx -g "daemon off;"
autostart       = true
autorestart     = true
directory       = /etc/nginx
startsecs       = 0

[program:mimir_1]
command         = node server.js
environment     =
    PORT=41011,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_2]
command         = node server.js
environment     =
    PORT=41012,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_3]
command         = node server.js
environment     =
    PORT=41013,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_4]
command         = node server.js
environment     =
    PORT=41014,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_5]
command         = node server.js
environment     =
    PORT=41015,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_6]
command         = node server.js
environment     =
    PORT=41016,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_7]
command         = node server.js
environment     =
    PORT=41017,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[program:mimir_8]
command         = node server.js
environment     =
    PORT=41018,
    NODE_ENV=production
autostart       = true
autorestart     = true
directory       = /var/www/html/Mimir-dist
startsecs       = 2
stopwaitsecs    = 2

[group:mimir]
programs=mimir_1,mimir_2,mimir_3,mimir_4,mimir_5,mimir_6,mimir_7,mimir_8
