<?php
/* NOTICE: autogenerated file; Do not edit by hand */
namespace FreyAccessManagement;
use Builtins\CJSModule;

class AccessRulesClass extends CJSModule {
    /**
     * @var (boolean|int|string)[] $rules
     */
    public $rules;
    /**
     * @return string
     */
    public function serialize() {
        return json_encode($this->rules);
    }
    /**
     * @param string $input
     * @return mixed
     */
    public function deserialize($input) {
        $this->rules = json_decode($input, true);
    }
}
