import type { EntityManager } from '@mikro-orm/core';
import { EventEntity } from '../entities/Event.entity.js';

export const eventRegisteredPlayers = (em: EntityManager) => [
  {
    id: 44,
    event: em.getReference(EventEntity, 19),
    playerId: 24,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 45,
    event: em.getReference(EventEntity, 19),
    playerId: 11,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 46,
    event: em.getReference(EventEntity, 19),
    playerId: 2,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 47,
    event: em.getReference(EventEntity, 19),
    playerId: 5,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 474,
    event: em.getReference(EventEntity, 19),
    playerId: 187,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 475,
    event: em.getReference(EventEntity, 19),
    playerId: 281,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 3455,
    event: em.getReference(EventEntity, 19),
    playerId: 10,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 5473,
    event: em.getReference(EventEntity, 19),
    playerId: 1516,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 6265,
    event: em.getReference(EventEntity, 19),
    playerId: 97,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 7827,
    event: em.getReference(EventEntity, 19),
    playerId: 131,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 9330,
    event: em.getReference(EventEntity, 19),
    playerId: 110,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 9331,
    event: em.getReference(EventEntity, 19),
    playerId: 195,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 9332,
    event: em.getReference(EventEntity, 19),
    playerId: 433,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14116,
    event: em.getReference(EventEntity, 19),
    playerId: 26,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14518,
    event: em.getReference(EventEntity, 19),
    playerId: 1411,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14522,
    event: em.getReference(EventEntity, 19),
    playerId: 3029,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14523,
    event: em.getReference(EventEntity, 19),
    playerId: 2883,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14545,
    event: em.getReference(EventEntity, 19),
    playerId: 1915,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14589,
    event: em.getReference(EventEntity, 19),
    playerId: 3018,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14898,
    event: em.getReference(EventEntity, 863),
    playerId: 73,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14899,
    event: em.getReference(EventEntity, 863),
    playerId: 2105,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14900,
    event: em.getReference(EventEntity, 863),
    playerId: 3091,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14901,
    event: em.getReference(EventEntity, 863),
    playerId: 1002,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14902,
    event: em.getReference(EventEntity, 863),
    playerId: 2815,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14903,
    event: em.getReference(EventEntity, 863),
    playerId: 961,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14904,
    event: em.getReference(EventEntity, 863),
    playerId: 2960,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14905,
    event: em.getReference(EventEntity, 863),
    playerId: 1151,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14906,
    event: em.getReference(EventEntity, 863),
    playerId: 2106,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14907,
    event: em.getReference(EventEntity, 863),
    playerId: 3071,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14908,
    event: em.getReference(EventEntity, 863),
    playerId: 573,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14909,
    event: em.getReference(EventEntity, 863),
    playerId: 2060,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14910,
    event: em.getReference(EventEntity, 863),
    playerId: 2597,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14911,
    event: em.getReference(EventEntity, 863),
    playerId: 50,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14912,
    event: em.getReference(EventEntity, 863),
    playerId: 2796,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14913,
    event: em.getReference(EventEntity, 863),
    playerId: 2931,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14914,
    event: em.getReference(EventEntity, 863),
    playerId: 2994,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14915,
    event: em.getReference(EventEntity, 863),
    playerId: 2482,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14916,
    event: em.getReference(EventEntity, 863),
    playerId: 1665,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14917,
    event: em.getReference(EventEntity, 863),
    playerId: 2572,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14920,
    event: em.getReference(EventEntity, 863),
    playerId: 156,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14921,
    event: em.getReference(EventEntity, 863),
    playerId: 51,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 14922,
    event: em.getReference(EventEntity, 863),
    playerId: 962,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15376,
    event: em.getReference(EventEntity, 863),
    playerId: 99,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15383,
    event: em.getReference(EventEntity, 889),
    playerId: 1002,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15384,
    event: em.getReference(EventEntity, 889),
    playerId: 1175,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15385,
    event: em.getReference(EventEntity, 889),
    playerId: 1468,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15393,
    event: em.getReference(EventEntity, 889),
    playerId: 2924,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15394,
    event: em.getReference(EventEntity, 889),
    playerId: 1407,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15395,
    event: em.getReference(EventEntity, 889),
    playerId: 2902,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15396,
    event: em.getReference(EventEntity, 889),
    playerId: 2572,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15397,
    event: em.getReference(EventEntity, 889),
    playerId: 2318,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15398,
    event: em.getReference(EventEntity, 889),
    playerId: 2033,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15399,
    event: em.getReference(EventEntity, 889),
    playerId: 304,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15400,
    event: em.getReference(EventEntity, 889),
    playerId: 235,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15401,
    event: em.getReference(EventEntity, 889),
    playerId: 1729,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15402,
    event: em.getReference(EventEntity, 889),
    playerId: 147,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15403,
    event: em.getReference(EventEntity, 889),
    playerId: 1028,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15404,
    event: em.getReference(EventEntity, 889),
    playerId: 2994,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15405,
    event: em.getReference(EventEntity, 889),
    playerId: 2387,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15406,
    event: em.getReference(EventEntity, 889),
    playerId: 1068,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15407,
    event: em.getReference(EventEntity, 889),
    playerId: 86,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15408,
    event: em.getReference(EventEntity, 889),
    playerId: 761,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15409,
    event: em.getReference(EventEntity, 889),
    playerId: 2597,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15410,
    event: em.getReference(EventEntity, 889),
    playerId: 948,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15411,
    event: em.getReference(EventEntity, 889),
    playerId: 1667,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15412,
    event: em.getReference(EventEntity, 889),
    playerId: 99,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15413,
    event: em.getReference(EventEntity, 889),
    playerId: 1834,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15414,
    event: em.getReference(EventEntity, 889),
    playerId: 338,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15415,
    event: em.getReference(EventEntity, 889),
    playerId: 743,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15416,
    event: em.getReference(EventEntity, 889),
    playerId: 2517,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15417,
    event: em.getReference(EventEntity, 889),
    playerId: 393,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15487,
    event: em.getReference(EventEntity, 863),
    playerId: 7,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
  {
    id: 15526,
    event: em.getReference(EventEntity, 863),
    playerId: 1891,
    localId: null,
    replacementId: null,
    ignoreSeating: 0,
  },
];
