{
 "title": "Pantheon service metrics",
 "tags": [ "Pantheon" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Currently played games / stale games",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pantheon_stale_games", "legendFormat": "stale games" },
    {
     "expr": "pantheon_played_games - pantheon_stale_games",
     "legendFormat": "played games"
    }
   ]
  },
  {
   "title": "Error log size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "pantheon_sys_errors", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Registered users count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pantheon_registered_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Events and achievements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pantheon_events_total_count", "legendFormat": "Total events" },
    {
     "expr": "pantheon_events_empty_count",
     "legendFormat": "Events without a single session"
    },
    { "expr": "pantheon_achievement_entries", "legendFormat": "Achievement entries count" }
   ]
  },
  {
   "title": "Jobs queue health",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pantheon_jobs_queue",
     "legendFormat": "Size of jobs queue (zero normally)"
    }
   ]
  }
 ]
}