{
 "title": "Pantheon service",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Rounds finished recently",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(pantheon_played_rounds[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Currently played games",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "pantheon_played_games - pantheon_stale_games",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stale games",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "pantheon_stale_games", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Registered users count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "pantheon_registered_users", "legendFormat": "__auto" }
   ]
  }
 ]
}