name: Build project artifacts & containers [arm64]

on:
  workflow_dispatch:
  push:
    paths:
      - 'Hermod/**'
      - '**/Dockerfile'
      - '**/Makefile'
      - '**/*.nginx.conf'
      - '**/entrypoint.sh'
      - 'docker-compose-amd64.yml'
      - 'docker-compose-arm64.yml'

jobs:
  buildContainers:
    runs-on: ubuntu-latest
    env:
      CONTAINER_ARCH_OVERRIDE: arm64
    if: |
      github.ref == 'refs/heads/master' &&
      github.repository == 'MahjongPantheon/pantheon'
    steps:
      - uses: actions/checkout@v2
      - run: apt-cache policy podman
      - uses: webgtx/setup-podman-compose@v1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Log in to container registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | podman login -u "${{ github.repository_owner }}" --password-stdin ghcr.io

      - name: Build and push [Backend common]
        run: |
          cd ./Common/Backend && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-backend-common-v3-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-backend-common-v3-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-backend-common-v3-arm64:latest; fi

      - name: Build and push [Frontend common]
        run: |
          cd ./Common/Frontend && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-frontend-common-v3-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-frontend-common-v3-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-frontend-common-v3-arm64:latest; fi

      - name: Build and push [Database]
        run: |
          cd ./Database && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-database-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-database-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-database-arm64:latest; fi

      - name: Build and push [Forseti]
        run: |
          cd ./Forseti && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-forseti-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-forseti-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-forseti-arm64:latest; fi

      - name: Build and push [Frey]
        run: |
          cd ./Frey && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-frey-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-frey-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-frey-arm64:latest; fi

      - name: Build and push [Hermod]
        run: |
          cd ./Hermod && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-hermod-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-hermod-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-hermod-arm64:latest; fi

      - name: Build and push [Hugin]
        run: |
          cd ./Hugin && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-hugin-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-hugin-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-hugin-arm64:latest; fi

      - name: Build and push [Gullveig]
        run: |
          cd ./Gullveig && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-gullveig-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-gullveig-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-gullveig-arm64:latest; fi

      - name: Build and push [Mimir]
        run: |
          cd ./Mimir && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-mimir-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-mimir-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-mimir-arm64:latest; fi

      - name: Build and push [Sigrun]
        run: |
          cd ./Sigrun && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-sigrun-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-sigrun-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-sigrun-arm64:latest; fi

      - name: Build and push [Bragi]
        run: |
          cd ./Bragi && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-bragi-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-bragi-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-bragi-arm64:latest; fi

      - name: Build and push [Skirnir]
        run: |
          cd ./Skirnir && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-skirnir-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-skirnir-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-skirnir-arm64:latest; fi

      - name: Build and push [Tyr]
        run: |
          cd ./Tyr && podman build --build-arg=CONTAINER_ARCH=arm64 --format docker --platform linux/arm64 \
            -t ghcr.io/mahjongpantheon/pantheon-tyr-arm64:latest \
            -t ghcr.io/mahjongpantheon/pantheon-tyr-arm64:${{ github.sha }} \
          .
          if [ "${{ github.event_name }}" != "pull_request" ]; then podman push ghcr.io/mahjongpantheon/pantheon-tyr-arm64:latest; fi
