name: Build project artifacts & containers [arm64]

on:
  workflow_dispatch:
  push:
    paths:
      - 'Hermod/**'
      - '**/Dockerfile'
      - '**/Makefile'
      - '**/*.nginx.conf'
      - '**/entrypoint.sh'
      - 'docker-compose-arm64.yml'

jobs:
  buildContainers:
    runs-on: ubuntu-latest
    env:
      CONTAINER_ARCH_OVERRIDE: arm64
    if: |
      github.ref == 'refs/heads/master' &&
      github.repository == 'MahjongPantheon/pantheon'
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push [Backend common]
        uses: docker/build-push-action@v6
        with:
          context: ./Common/Backend
          build-args: CONTAINER_ARCH=arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-backend-common-v3-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-backend-common-v3-arm64:${{ github.sha }}

      - name: Build and push [Frontend common]
        uses: docker/build-push-action@v6
        with:
          context: ./Common/Frontend
          build-args: CONTAINER_ARCH=arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-frontend-common-v3-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-frontend-common-v3-arm64:${{ github.sha }}

      - name: Build and push [Database]
        uses: docker/build-push-action@v6
        with:
          context: ./Database
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-database-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-database-arm64:${{ github.sha }}

      - name: Build and push [Redis]
        uses: docker/build-push-action@v6
        with:
          context: ./Redis
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-redis-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-redis-arm64:${{ github.sha }}

      - name: Build and push [Forseti]
        uses: docker/build-push-action@v6
        with:
          context: ./Forseti
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-forseti-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-forseti-arm64:${{ github.sha }}

      - name: Build and push [Frey]
        uses: docker/build-push-action@v6
        with:
          context: ./Frey
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-frey-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-frey-arm64:${{ github.sha }}

      - name: Build and push [Hermod]
        uses: docker/build-push-action@v6
        with:
          context: ./Hermod
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-hermod-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-hermod-arm64:${{ github.sha }}

      - name: Build and push [Hugin]
        uses: docker/build-push-action@v6
        with:
          context: ./Hugin
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-hugin-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-hugin-arm64:${{ github.sha }}

      - name: Build and push [Gullveig]
        uses: docker/build-push-action@v6
        with:
          context: ./Gullveig
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-gullveig-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-gullveig-arm64:${{ github.sha }}

      - name: Build and push [Mimir]
        uses: docker/build-push-action@v6
        with:
          context: ./Mimir
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-mimir-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-mimir-arm64:${{ github.sha }}

      - name: Build and push [Sigrun]
        uses: docker/build-push-action@v6
        with:
          context: ./Sigrun
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-sigrun-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-sigrun-arm64:${{ github.sha }}

      - name: Build and push [Bragi]
        uses: docker/build-push-action@v6
        with:
          context: ./Bragi
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-bragi-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-bragi-arm64:${{ github.sha }}

      - name: Build and push [Skirnir]
        uses: docker/build-push-action@v6
        with:
          context: ./Skirnir
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-skirnir-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-skirnir-arm64:${{ github.sha }}

      - name: Build and push [Tyr]
        uses: docker/build-push-action@v6
        with:
          context: ./Tyr
          platforms: linux/arm64
          build-args: CONTAINER_ARCH=arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-tyr-arm64:latest
            ghcr.io/mahjongpantheon/pantheon-tyr-arm64:${{ github.sha }}
