name: Unit tests, static analysis, code style

on:
  workflow_dispatch:
  push:

jobs:
  checkPr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: webgtx/setup-podman-compose@v1

      - uses: NathanFirmo/wait-for-other-action@v1.0.4
        if: |
          github.ref == 'refs/heads/master' &&
          github.repository == 'MahjongPantheon/pantheon'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'build.yml'

      - name: Reset podman & disable apparmor
        run: |
          sudo aa-teardown || true
          sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER
          sudo systemctl disable --now apparmor.service
          sudo rm -f /etc/containers/storage.conf || true
          podman system reset -f
          sudo podman system reset -f

      - name: Print env
        run: env

      - name: Pull containers
        run: make pull

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all code checks
        run: make lint

      - name: Run all unit tests
        run: make test

      - name: Stop containers
        if: always()
        run: make pantheon_stop

