name: Unit tests, static analysis, code style [arm64]

on:
  workflow_dispatch:
  push:

jobs:
  checkPr:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v2
      - uses: webgtx/setup-podman-compose@v1

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all code checks
        run: make lint

      - name: Run all unit tests
        run: make test

      - name: Stop containers
        if: always()
        run: make pantheon_stop

