name: Unit tests, static analysis, code style [arm64]

on:
  workflow_dispatch:
  push:

jobs:
  checkPr:
    runs-on: ubuntu-latest
    env:
      CONTAINER_ARCH_OVERRIDE: arm64
    steps:
      - uses: actions/checkout@v2
      - uses: webgtx/setup-podman-compose@v1

      - uses: NathanFirmo/wait-for-other-action@v1.0.4
        if: |
          github.ref == 'refs/heads/master' &&
          github.repository == 'MahjongPantheon/pantheon'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          workflow: 'build-arm64.yml'

      - name: Reset podman
        run: podman system reset -f

      - name: Print env
        run: env

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Pull containers
        run: make pull

      - name: Run container
        run: make pantheon_run

      - name: Install project deps
        run: make deps

      - name: Apply db migrations
        run: make migrate

      - name: Run all code checks
        run: make lint

      - name: Run all unit tests
        run: make test

      - name: Stop containers
        if: always()
        run: make pantheon_stop

