name: Build container for e2e testing [arm64]

on:
  workflow_dispatch:
  push:
    paths:
      - 'Fenrir/**'

jobs:
  e2eBuildContainer:
    runs-on: ubuntu-latest
    env:
      CONTAINER_ARCH_OVERRIDE: arm64
    if: |
      github.ref == 'refs/heads/master' &&
      github.repository == 'MahjongPantheon/pantheon'
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push [Fenrir]
        uses: docker/build-push-action@v6
        with:
          context: ./Fenrir
          build-args: CONTAINER_ARCH=arm64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ghcr.io/mahjongpantheon/pantheon-fenrir-amd64:latest
            ghcr.io/mahjongpantheon/pantheon-fenrir-amd64:${{ github.sha }}

